[book]
title = "vinib"
authors = ["Vini Barbosa"]
description = "Technical writing, docs engineering, devrel, and web3 portfolio by Vini Barbosa"
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/vinibarbosabr/vinib-portfolio"
# edit-url-template = "https://github.com/vinibarbosabr/vinib-portfolio/edit/main/{path}"
site-url = "/"
# TODO: additional-css = ["theme/custom.css"]

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30
use-boolean-and = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]
